CREATE TABLE IF NOT EXISTS site_info (
  site_info_id INT(10) NOT NULL AUTO_INCREMENT,
  site_name VARCHAR(255) NOT NULL,
  site_url VARCHAR(1024) NOT NULL,
  logo_url VARCHAR(256) DEFAULT NULL,
  contract_type CHAR(1) NOT NULL DEFAULT '0' COMMENT '0:NONE,1:partner,2:reprint,9:other',
  delete_flg CHAR(1) NOT NULL DEFAULT '0' COMMENT '1:delete',
  contents_type CHAR(1) NOT NULL DEFAULT '1' COMMENT '1:html, 2:wordpress',
  PRIMARY KEY (site_info_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE site_info
  ADD COLUMN contract_type CHAR(1) NOT NULL DEFAULT '0' COMMENT '0:NONE,1:partner,2:reprint,9:other'
  AFTER logo_url;

CREATE TABLE IF NOT EXISTS site_category (
  site_category_id INT(10) NOT NULL AUTO_INCREMENT,
  site_info_id INT(10) NOT NULL,
  cms_category_id INT(10) DEFAULT NULL,
  source_category_id INT(10) DEFAULT NULL,
  category_name VARCHAR(256) NOT NULL,
  delete_flg CHAR(1) NOT NULL DEFAULT '0' COMMENT '1:delete',
  category_url VARCHAR(256) NOT NULL,
  category_list_url VARCHAR(256) DEFAULT NULL,
  last_scan_time DATETIME DEFAULT NULL,
  target_category VARCHAR(256) DEFAULT NULL,
  cms_target_category VARCHAR(256) DEFAULT NULL,
  list_record_select_id VARCHAR(256) NOT NULL,
  title_record_select_id VARCHAR(256) NOT NULL,
  contents_url_selectId VARCHAR(256) NOT NULL,
  body_select_id VARCHAR(256) NOT NULL,
  more_body_select_id VARCHAR(256) NOT NULL,
  more_body_select_txt VARCHAR(256) DEFAULT NULL,
  PRIMARY KEY (site_category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE site_category
  ADD COLUMN cms_category_id INT(10) DEFAULT NULL
  AFTER site_info_id;

ALTER TABLE site_category
  ADD COLUMN source_category_id INT(10) DEFAULT NULL
  AFTER cms_category_id;

ALTER TABLE site_category
  ADD COLUMN delete_flg CHAR(1) NOT NULL DEFAULT '0' COMMENT '1:delete'
  AFTER category_name;

ALTER TABLE site_category
  ADD COLUMN category_list_url VARCHAR(256) DEFAULT NULL
  AFTER category_url;

ALTER TABLE site_category
  ADD COLUMN last_scan_time DATETIME DEFAULT NULL
  AFTER category_list_url;

ALTER TABLE site_category
  ADD COLUMN target_category VARCHAR(256) DEFAULT NULL
  AFTER last_scan_time;

ALTER TABLE site_category
  ADD COLUMN cms_target_category VARCHAR(256) DEFAULT NULL
  AFTER target_category;

ALTER TABLE site_category
  ADD COLUMN list_record_select_id VARCHAR(256) NOT NULL DEFAULT ''
  AFTER cms_target_category;

ALTER TABLE site_category
  ADD COLUMN title_record_select_id VARCHAR(256) NOT NULL DEFAULT ''
  AFTER list_record_select_id;

ALTER TABLE site_category
  ADD COLUMN contents_url_selectId VARCHAR(256) NOT NULL DEFAULT ''
  AFTER title_record_select_id;

ALTER TABLE site_category
  ADD COLUMN body_select_id VARCHAR(256) NOT NULL DEFAULT ''
  AFTER contents_url_selectId;

ALTER TABLE site_category
  ADD COLUMN more_body_select_id VARCHAR(256) NOT NULL DEFAULT ''
  AFTER body_select_id;

ALTER TABLE site_category
  ADD COLUMN more_body_select_txt VARCHAR(256) DEFAULT NULL
  AFTER more_body_select_id;

CREATE TABLE IF NOT EXISTS site_contents (
  site_contents_id BIGINT(20) NOT NULL AUTO_INCREMENT,
  url VARCHAR(1024) NOT NULL,
  requested_url VARCHAR(2048) DEFAULT NULL,
  redirected_url VARCHAR(2048) DEFAULT NULL,
  canonical_url VARCHAR(2048) DEFAULT NULL,
  normalized_url VARCHAR(2048) DEFAULT NULL,
  normalized_url_hash CHAR(64) NOT NULL,
  source_url VARCHAR(2048) DEFAULT NULL,
  title TEXT NOT NULL,
  description TEXT NULL,
  contents TEXT NOT NULL,
  featured_image_url VARCHAR(1024) DEFAULT NULL,
  site_categoy_id INT(10) NOT NULL,
  process_status CHAR(1) NOT NULL DEFAULT '1' COMMENT '1:NONE,2:processing,3:fail,4:success',
  cms_content_id BIGINT(20) DEFAULT NULL,
  PRIMARY KEY (site_contents_id),
  UNIQUE KEY url (url(255)),
  UNIQUE KEY uk_site_contents_normalized_url_hash (normalized_url_hash)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE site_contents
  ADD COLUMN description TEXT NULL
  AFTER title;

ALTER TABLE site_contents
  ADD COLUMN cms_content_id BIGINT(20) DEFAULT NULL
  AFTER process_status;

ALTER TABLE site_contents
  ADD COLUMN featured_image_url VARCHAR(1024) DEFAULT NULL
  AFTER contents;

ALTER TABLE site_contents
  ADD COLUMN requested_url VARCHAR(2048) DEFAULT NULL,
  ADD COLUMN redirected_url VARCHAR(2048) DEFAULT NULL,
  ADD COLUMN canonical_url VARCHAR(2048) DEFAULT NULL,
  ADD COLUMN normalized_url VARCHAR(2048) DEFAULT NULL,
  ADD COLUMN normalized_url_hash CHAR(64) DEFAULT NULL,
  ADD COLUMN source_url VARCHAR(2048) DEFAULT NULL;

UPDATE site_contents
SET requested_url = url,
    normalized_url = url,
    normalized_url_hash = LOWER(SHA2(url, 256)),
    source_url = url
WHERE normalized_url_hash IS NULL;

ALTER TABLE site_contents
  MODIFY normalized_url_hash CHAR(64) NOT NULL,
  ADD UNIQUE KEY uk_site_contents_normalized_url_hash (normalized_url_hash);

CREATE TABLE IF NOT EXISTS site_info_process_pool (
  site_info_process_id INT(10) NOT NULL AUTO_INCREMENT,
  site_category_id INT(10) NOT NULL,
  process_status CHAR(1) NOT NULL DEFAULT '0' COMMENT '1:NONE,2:processing,3:fail,4:success',
  process_id VARCHAR(191) DEFAULT NULL,
  owner_instance VARCHAR(96) DEFAULT NULL,
  lease_attempt BIGINT NOT NULL DEFAULT 0,
  claimed_at DATETIME(6) DEFAULT NULL,
  heartbeat_at DATETIME(6) DEFAULT NULL,
  last_result_status CHAR(1) DEFAULT NULL,
  process_time DATETIME(6) DEFAULT NULL,
  PRIMARY KEY (site_info_process_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE site_info_process_pool
  MODIFY process_id VARCHAR(191) DEFAULT NULL,
  ADD COLUMN owner_instance VARCHAR(96) DEFAULT NULL,
  ADD COLUMN lease_attempt BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN claimed_at DATETIME(6) DEFAULT NULL,
  ADD COLUMN heartbeat_at DATETIME(6) DEFAULT NULL,
  ADD COLUMN last_result_status CHAR(1) DEFAULT NULL;

CREATE INDEX idx_process_pool_claim
  ON site_info_process_pool (process_status, heartbeat_at, process_time);

ALTER TABLE site_info_process_pool
  ADD UNIQUE KEY uk_process_pool_site_category (site_category_id);

CREATE TABLE IF NOT EXISTS BATCH_JOB_INSTANCE (
  JOB_INSTANCE_ID BIGINT NOT NULL PRIMARY KEY,
  VERSION BIGINT,
  JOB_NAME VARCHAR(100) NOT NULL,
  JOB_KEY VARCHAR(32) NOT NULL,
  CONSTRAINT JOB_INST_UN UNIQUE (JOB_NAME, JOB_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION (
  JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
  VERSION BIGINT,
  JOB_INSTANCE_ID BIGINT NOT NULL,
  CREATE_TIME DATETIME NOT NULL,
  START_TIME DATETIME DEFAULT NULL,
  END_TIME DATETIME DEFAULT NULL,
  STATUS VARCHAR(10),
  EXIT_CODE VARCHAR(2500),
  EXIT_MESSAGE VARCHAR(2500),
  LAST_UPDATED DATETIME,
  CONSTRAINT JOB_INST_EXEC_FK FOREIGN KEY (JOB_INSTANCE_ID)
    REFERENCES BATCH_JOB_INSTANCE(JOB_INSTANCE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_PARAMS (
  JOB_EXECUTION_ID BIGINT NOT NULL,
  PARAMETER_NAME VARCHAR(100) NOT NULL,
  PARAMETER_TYPE VARCHAR(100) NOT NULL,
  PARAMETER_VALUE VARCHAR(2500),
  IDENTIFYING CHAR(1) NOT NULL,
  CONSTRAINT JOB_EXEC_PARAMS_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION (
  STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
  VERSION BIGINT NOT NULL,
  STEP_NAME VARCHAR(100) NOT NULL,
  JOB_EXECUTION_ID BIGINT NOT NULL,
  CREATE_TIME DATETIME NOT NULL,
  START_TIME DATETIME DEFAULT NULL,
  END_TIME DATETIME DEFAULT NULL,
  STATUS VARCHAR(10),
  COMMIT_COUNT BIGINT,
  READ_COUNT BIGINT,
  FILTER_COUNT BIGINT,
  WRITE_COUNT BIGINT,
  READ_SKIP_COUNT BIGINT,
  WRITE_SKIP_COUNT BIGINT,
  PROCESS_SKIP_COUNT BIGINT,
  ROLLBACK_COUNT BIGINT,
  EXIT_CODE VARCHAR(2500),
  EXIT_MESSAGE VARCHAR(2500),
  LAST_UPDATED DATETIME,
  CONSTRAINT JOB_EXEC_STEP_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_CONTEXT (
  STEP_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
  SHORT_CONTEXT VARCHAR(2500) NOT NULL,
  SERIALIZED_CONTEXT TEXT,
  CONSTRAINT STEP_EXEC_CTX_FK FOREIGN KEY (STEP_EXECUTION_ID)
    REFERENCES BATCH_STEP_EXECUTION(STEP_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_CONTEXT (
  JOB_EXECUTION_ID BIGINT NOT NULL PRIMARY KEY,
  SHORT_CONTEXT VARCHAR(2500) NOT NULL,
  SERIALIZED_CONTEXT TEXT,
  CONSTRAINT JOB_EXEC_CTX_FK FOREIGN KEY (JOB_EXECUTION_ID)
    REFERENCES BATCH_JOB_EXECUTION(JOB_EXECUTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS BATCH_STEP_EXECUTION_SEQ (
  ID BIGINT NOT NULL,
  UNIQUE_KEY CHAR(1) NOT NULL,
  CONSTRAINT BATCH_STEP_EXECUTION_SEQ_UN UNIQUE (UNIQUE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO BATCH_STEP_EXECUTION_SEQ (ID, UNIQUE_KEY)
SELECT * FROM (SELECT 0 AS ID, '0' AS UNIQUE_KEY) AS tmp
WHERE NOT EXISTS (SELECT * FROM BATCH_STEP_EXECUTION_SEQ);

CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION_SEQ (
  ID BIGINT NOT NULL,
  UNIQUE_KEY CHAR(1) NOT NULL,
  CONSTRAINT BATCH_JOB_EXECUTION_SEQ_UN UNIQUE (UNIQUE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO BATCH_JOB_EXECUTION_SEQ (ID, UNIQUE_KEY)
SELECT * FROM (SELECT 0 AS ID, '0' AS UNIQUE_KEY) AS tmp
WHERE NOT EXISTS (SELECT * FROM BATCH_JOB_EXECUTION_SEQ);

CREATE TABLE IF NOT EXISTS BATCH_JOB_SEQ (
  ID BIGINT NOT NULL,
  UNIQUE_KEY CHAR(1) NOT NULL,
  CONSTRAINT BATCH_JOB_SEQ_UN UNIQUE (UNIQUE_KEY)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO BATCH_JOB_SEQ (ID, UNIQUE_KEY)
SELECT * FROM (SELECT 0 AS ID, '0' AS UNIQUE_KEY) AS tmp
WHERE NOT EXISTS (SELECT * FROM BATCH_JOB_SEQ);
