package com.happinesea.webcrawler.config;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.lenient;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;
import static org.mockito.Mockito.when;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.batch.core.JobExecution;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.JobParametersBuilder;
import org.springframework.batch.core.Step;
import org.springframework.batch.core.StepExecution;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.item.Chunk;
import org.springframework.batch.item.ExecutionContext;
import org.springframework.batch.item.ItemProcessor;
import org.springframework.batch.item.ItemReader;
import org.springframework.batch.item.ItemStreamReader;
import org.springframework.batch.item.ItemWriter;
import org.springframework.batch.item.support.ListItemReader;
import org.springframework.batch.item.support.SynchronizedItemStreamReader;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.core.task.TaskExecutor;
import org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.util.ReflectionTestUtils;
import org.springframework.transaction.PlatformTransactionManager;

import com.happinesea.webcrawler.ContentsParser;
import com.happinesea.webcrawler.NotFoundContentsException;
import com.happinesea.webcrawler.entity.SiteCategory;
import com.happinesea.webcrawler.entity.SiteContents;
import com.happinesea.webcrawler.entity.SiteInfo;
import com.happinesea.webcrawler.entity.SiteInfoProcessPool;
import com.happinesea.webcrawler.repository.SiteCategoryRepository;
import com.happinesea.webcrawler.repository.SiteContentsRepository;
import com.happinesea.webcrawler.repository.SiteInfoProcessRepository;
import com.happinesea.webcrawler.repository.SiteInfoRepository;
import com.happinesea.webcrawler.service.SiteContentsService;

@SpringBootTest
@ActiveProfiles("test")
@AutoConfigureTestDatabase
@ExtendWith(MockitoExtension.class)
class CrawlerComponentsTest {

	@Mock
	private SiteContentsService siteContentsServiceMock;

	@Mock
	private SiteInfoProcessRepository siteInfoProcessRepository;

	@Mock
	private ContentsParser contentsParser;

	@Autowired
	private CrawlerComponents crawlerComponents;
	@Autowired
	private SiteInfoRepository siteInfoRepository;
	@Autowired
	private SiteCategoryRepository siteCategoryRepository;
	@Autowired
	private SiteContentsRepository siteContentsRepository;
	@Autowired
	private JobRepository jobRepository;
	@Autowired
	private PlatformTransactionManager transactionManager;

	private SiteInfoProcessPool process;
	private SiteCategory category;
	private SiteContents contents;
	private List<SiteContents> contentsList;

	@BeforeEach
	void setup() {
		SiteInfo siteInfo = new SiteInfo();
		siteInfo.setSiteUrl("https://example.com");
		// ID is generated by DB.
		siteInfo = siteInfoRepository.save(siteInfo);

		category = new SiteCategory();
		category.setCategoryName("news");
		category.setCategoryUrl("https://example.com/news");
		category.setSiteInfo(siteInfo);
		category = siteCategoryRepository.save(category);

		contents = new SiteContents();
		contents.setTitle("article title");
		contents.setUrl("https://example.com/article");
		contents.setSiteCategory(category);
		contents = siteContentsRepository.save(contents);

		process = new SiteInfoProcessPool();
		process.setSiteCategory(category);
		process.setSiteInfoProcessId(1);
		process.setProcessStatus(com.happinesea.webcrawler.Const.ProcessStatus.PROCESSING);
		process.setProcessId("job-manual");

		contentsList = new ArrayList<>();
		contentsList.add(contents);

		crawlerComponents.setContentsParser(contentsParser);
		crawlerComponents.setSiteContentsService(siteContentsServiceMock);
		lenient().when(siteContentsServiceMock.claimSiteInfoProcess(any(), anyString()))
				.thenReturn(Optional.of(process));
		lenient().when(siteContentsServiceMock.saveAllProcessPools(any())).thenReturn(List.of(process));
	}

	@Test
	void testSiteInfoProcessor_shouldCallLoadMethodsAndUpdateStatus() throws Exception {

		when(contentsParser.loadCategoryContentsList(category)).thenReturn(List.of(contents));
		when(contentsParser.loadContents(contents)).thenReturn(contents);

		// Act
		SiteInfoProcessPool result = crawlerComponents.siteInfoProcessor().process(process);

		// Assert
		assertEquals(process, result);
		verify(contentsParser).loadCategoryContentsList(category);
		verify(contentsParser).loadContents(contents);
		verify(siteContentsServiceMock).claimSiteInfoProcess(any(), anyString());
	}

	@Test
	void duplicateOnlyCategoryIsSuccessfulAndStillReleasesItsPool() throws Exception {
		when(contentsParser.loadCategoryContentsList(category)).thenReturn(List.of(contents));
		when(contentsParser.loadContents(contents)).thenReturn(contents);
		when(siteContentsServiceMock.bulkInsertIfNotExists(List.of(contents))).thenReturn(List.of());

		SiteInfoProcessPool result = crawlerComponents.siteInfoProcessor().process(process);

		assertEquals(process, result);
		verify(siteContentsServiceMock).saveAllProcessPools(List.of(process));
	}

	@Test
	void repairModeSkipsCategoryCrawlAndRunsConfiguredRepairOnly() throws Exception {
		when(siteContentsServiceMock.isCmsRepairConfigured()).thenReturn(true);
		when(siteContentsServiceMock.repairConfiguredCmsContent(any())).thenReturn(List.of(process));

		SiteInfoProcessPool result = crawlerComponents.siteInfoProcessor().process(process);

		assertEquals(process, result);
		verify(siteContentsServiceMock).repairConfiguredCmsContent(any());
		verifyNoInteractions(contentsParser);
	}

	@Test
	void testSiteInfoProcessor_shouldHandleExceptionAndSetFailStatus() throws Exception {
		when(contentsParser.loadCategoryContentsList(category)).thenThrow(new RuntimeException("read failed"));

		assertNull(crawlerComponents.siteInfoProcessor().process(process));

		verify(siteContentsServiceMock).claimSiteInfoProcess(any(), anyString());
		verify(siteContentsServiceMock).finishOwnedProcess(any(SiteInfoProcessPool.class), any());
	}

	@Test
	void testSiteInfoProcessWriter_shouldInsertContentsAndUpdateStatus() throws Exception {
		process.setSiteCategory(category);
		ItemWriter<SiteInfoProcessPool> writer = crawlerComponents.siteInfoProcessWriter();

		writer.write(new Chunk<>(List.of(process)));

		verifyNoInteractions(siteInfoProcessRepository);
	}

	@Test
	void testSiteInfoProcessReaderWhenTargetListIsNullReturnsEmptyReader() throws Exception {
		ItemReader<SiteInfoProcessPool> reader = crawlerComponents.siteInfoProcessReader(null);

		assertNull(reader.read());
	}

	@Test
	void testSiteInfoProcessorLimitsLoadedContentsBeforeFetchingDetails() throws Exception {
		ReflectionTestUtils.setField(crawlerComponents, "crawlContentLimitCount", 1);
		SiteContents second = new SiteContents();
		second.setTitle("second");
		second.setUrl("https://example.com/second");
		second.setSiteCategory(category);

		when(contentsParser.loadCategoryContentsList(category)).thenReturn(List.of(contents, second));
		when(contentsParser.loadContents(contents)).thenReturn(contents);

		SiteInfoProcessPool result = crawlerComponents.siteInfoProcessor().process(process);

		assertEquals(process, result);
		verify(contentsParser).loadContents(contents);
		verify(contentsParser, never()).loadContents(second);
	}

	@Test
	void testParallelExecution_withMultipleThreads() throws Exception {
		// Create JobExecution from JobRepository.
		JobParameters jobParameters = new JobParametersBuilder().addLong("time", System.currentTimeMillis())
				.toJobParameters();
		JobExecution jobExecution = jobRepository.createJobExecution("testJob", jobParameters);

		// Create StepExecution from JobExecution.
		StepExecution stepExecution = jobExecution.createStepExecution("testStep");
		jobRepository.add(stepExecution);

		// Prepare test items.
		List<SiteInfoProcessPool> items = new ArrayList<>();
		for (int i = 0; i < 10; i++) {
			SiteInfoProcessPool item = new SiteInfoProcessPool();
			item.setProcessId(String.valueOf(i));
			items.add(item);
		}

		// Build ItemReader.
		ItemReader<SiteInfoProcessPool> listReader = new ListItemReader<>(items);
		ItemStreamReader<SiteInfoProcessPool> streamReader = new ItemStreamReader<>() {
			@Override
			public SiteInfoProcessPool read() {
				try {
					return listReader.read();
				} catch (Exception e) {
					return null;
				}
			}

			@Override
			public void open(ExecutionContext executionContext) {
			}

			@Override
			public void update(ExecutionContext executionContext) {
			}

			@Override
			public void close() {
			}
		};

		SynchronizedItemStreamReader<SiteInfoProcessPool> synchronizedReader = new SynchronizedItemStreamReader<>();
		synchronizedReader.setDelegate(streamReader);

		// Processor and Writer.
		ItemProcessor<SiteInfoProcessPool, SiteInfoProcessPool> processor = item -> {
			System.out.println(Thread.currentThread().getName() + " processing ID = " + item.getProcessId());
			return item;
		};

		ItemWriter<SiteInfoProcessPool> writer = chunk -> {
			for (SiteInfoProcessPool item : chunk) {
				System.out.println(Thread.currentThread().getName() + " writing ID = " + item.getProcessId());
			}
		};

		// TaskExecutor.
		TaskExecutor executor = createTaskExecutor();

		// Build Step.
		Step step = new StepBuilder("testStep", jobRepository)
				.<SiteInfoProcessPool, SiteInfoProcessPool>chunk(2, transactionManager).reader(synchronizedReader)
				.processor(processor).writer(writer).taskExecutor(executor).build();

		// Execute Step.
		step.execute(stepExecution);

		System.out.println("Completed all steps.");
	}

	private TaskExecutor createTaskExecutor() {
		ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
		executor.setCorePoolSize(10);
		executor.setMaxPoolSize(20);
		executor.setQueueCapacity(100);
		executor.setThreadNamePrefix("test-thread-");
		executor.initialize();
		return executor;
	}

	@Test
	void testSiteInfoProcessor_shouldHandleNotFoundContentsException() throws Exception {
		when(contentsParser.loadCategoryContentsList(category)).thenReturn(List.of(contents));
		when(contentsParser.loadContents(contents)).thenThrow(new NotFoundContentsException("not found"));

		assertNull(crawlerComponents.siteInfoProcessor().process(process));

		verify(contentsParser).loadCategoryContentsList(category);
		verify(contentsParser).loadContents(contents);
		verify(siteContentsServiceMock).finishOwnedProcess(process, com.happinesea.webcrawler.Const.ProcessStatus.FAIL);
	}
	@Test
	void testSiteInfoProcessor_shouldFailWhenContentsListIsNull() throws Exception {
		when(contentsParser.loadCategoryContentsList(category)).thenReturn(null);

		assertNull(crawlerComponents.siteInfoProcessor().process(process));

		verify(siteContentsServiceMock).finishOwnedProcess(process, com.happinesea.webcrawler.Const.ProcessStatus.FAIL);
		verify(contentsParser).loadCategoryContentsList(category);
		verify(contentsParser, never()).loadContents(any());
	}
	@Test
	void testSiteInfoProcessor_shouldFailWhenContentsListIsEmpty() throws Exception {
		when(contentsParser.loadCategoryContentsList(category)).thenReturn(Collections.emptyList());

		assertNull(crawlerComponents.siteInfoProcessor().process(process));

		verify(siteContentsServiceMock).finishOwnedProcess(process, com.happinesea.webcrawler.Const.ProcessStatus.FAIL);
		verify(contentsParser).loadCategoryContentsList(category);
		verify(contentsParser, never()).loadContents(any());
	}
}
